#!/usr/bin/env node
/**
 * Daily Summary Generator
 * Runs at 10 PM via cron
 * Uses Claude to analyze ActivityWatch data and generate daily log
 */

const fs = require('fs').promises;
const path = require('path');
const { execSync } = require('child_process');
const { ClaudeClient } = require('../lib/claude-client');

// Configuration
const CONFIG = {
  logsDir: path.join(__dirname, '..', 'logs'),
  baseDir: path.join(__dirname, '..')
};

// Get today's file paths
function getTodayPaths() {
  const now = new Date();
  const year = String(now.getFullYear());
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');

  return {
    dir: path.join(CONFIG.logsDir, year, month),
    activityFile: path.join(CONFIG.logsDir, year, month, `${year}-${month}-${day}-activity.json`),
    summaryFile: path.join(CONFIG.logsDir, year, month, `${year}-${month}-${day}.md`),
    indexFile: path.join(CONFIG.logsDir, year, month, 'index.md'),
    year,
    month,
    day
  };
}

// Load activity data
async function loadActivityData(filePath) {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    return JSON.parse(content);
  } catch (err) {
    console.error('Failed to load activity data:', err.message);
    return null;
  }
}

// Load manual tasks from server storage
async function loadManualTasks() {
  try {
    const tasksFile = path.join(CONFIG.baseDir, 'data', 'manual-tasks.json');
    const content = await fs.readFile(tasksFile, 'utf-8');
    return JSON.parse(content);
  } catch (err) {
    return [];
  }
}

// Generate markdown from Claude analysis
function generateMarkdown(analysis, activityData) {
  const date = activityData?.date || new Date().toISOString().split('T')[0];
  const timestamp = new Date().toISOString();

  let md = `---
date: ${date}
generated: ${timestamp}
hours_active: ${analysis.hours_active || 0}
hours_coding: ${analysis.hours_coding || 0}
hours_meetings: ${analysis.hours_meetings || 0}
hours_research: ${analysis.hours_research || 0}
commits_today: ${analysis.commits_today || 0}
projects: [${(analysis.projects || []).join(', ')}]
tags: [${(analysis.tags || []).join(', ')}]
---

# Daily Work Log - ${date}

## Activity Summary

| Category | Hours |
|----------|-------|
| Active Time | ${analysis.hours_active || 0} |
| Coding | ${analysis.hours_coding || 0} |
| Meetings | ${analysis.hours_meetings || 0} |
| Research | ${analysis.hours_research || 0} |

### Time Distribution
${analysis.activity_summary?.time_distribution || 'No data available'}

### Focus Areas
${(analysis.activity_summary?.focus_areas || []).map(area => `- ${area}`).join('\n')}

---

## Work Analysis

### Completed Tasks
${(analysis.completed_tasks || []).map(task => `- [x] ${task}`).join('\n') || '- No completed tasks detected'}

### In Progress
${(analysis.in_progress || []).map(task => `- [ ] ${task}`).join('\n') || '- No in-progress items detected'}

### Research & Learning
${(analysis.research_learning || []).map(item => `- ${item}`).join('\n') || '- No research activities detected'}

### Blockers
${(analysis.blockers || []).map(item => `- ${item}`).join('\n') || '- No blockers identified'}

---

## AI Insights
${(analysis.ai_insights || []).map(insight => `- ${insight}`).join('\n') || '- No insights available'}

---

## Tomorrow's Plan
${(analysis.tomorrow_plan || []).map(item => `- [ ] ${item}`).join('\n') || '- No plan generated'}

---

*Auto-generated by Claude at ${timestamp}*
`;
  return md;
}

// Update monthly index
async function updateMonthlyIndex(paths) {
  const indexContent = `# ${paths.year} - ${getMonthName(paths.month)} Summary

## Daily Logs

| Date | Hours Active | Commits | Projects |
|------|--------------|---------|----------|
{{DAILY_ROWS}}

---
*Auto-updated on ${new Date().toISOString()}*
`;

  // Read all daily logs in the month
  let rows = [];
  try {
    const files = await fs.readdir(paths.dir);
    const mdFiles = files.filter(f => f.match(/^\d{4}-\d{2}-\d{2}\.md$/));

    for (const file of mdFiles) {
      try {
        const content = await fs.readFile(path.join(paths.dir, file), 'utf-8');
        const frontmatter = parseFrontmatter(content);
        const date = file.replace('.md', '');

        rows.push(`| ${date} | ${frontmatter.hours_active || 0} | ${frontmatter.commits_today || 0} | ${(frontmatter.projects || []).join(', ')} |`);
      } catch (e) {}
    }
  } catch (err) {}

  const finalContent = indexContent.replace('{{DAILY_ROWS}}', rows.join('\n'));
  await fs.writeFile(paths.indexFile, finalContent);
}

function parseFrontmatter(content) {
  const match = content.match(/---\n([\s\S]+?)\n---/);
  if (!match) return {};

  const frontmatter = {};
  match[1].split('\n').forEach(line => {
    const [key, ...valueParts] = line.split(':');
    if (key && valueParts.length) {
      let value = valueParts.join(':').trim();
      // Parse arrays
      if (value.startsWith('[') && value.endsWith(']')) {
        value = value.slice(1, -1).split(',').map(s => s.trim()).filter(Boolean);
      } else if (!isNaN(value)) {
        value = parseFloat(value);
      }
      frontmatter[key.trim()] = value;
    }
  });

  return frontmatter;
}

function getMonthName(month) {
  const months = ['January', 'February', 'March', 'April', 'May', 'June',
                  'July', 'August', 'September', 'October', 'November', 'December'];
  return months[parseInt(month) - 1];
}

// Git operations
async function commitAndPush(message) {
  try {
    execSync('git add .', { cwd: CONFIG.baseDir, stdio: 'inherit' });
    execSync(`git commit -m "${message}"`, { cwd: CONFIG.baseDir, stdio: 'inherit' });
    execSync('git push', { cwd: CONFIG.baseDir, stdio: 'inherit' });
    console.log('Successfully committed and pushed to GitHub');
  } catch (err) {
    if (!err.message.includes('nothing to commit')) {
      console.error('Git error:', err.message);
    }
  }
}

// Main function
async function main() {
  console.log('=== Daily Summary Generator Started ===');
  console.log('Time:', new Date().toISOString());

  // Check for API key
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('ERROR: ANTHROPIC_API_KEY environment variable is not set');
    console.error('Please set it in your .env file or environment');
    process.exit(1);
  }

  const paths = getTodayPaths();

  // Load activity data
  const activityData = await loadActivityData(paths.activityFile);
  if (!activityData) {
    console.error('No activity data found for today. Run collect-activity.js first.');
    process.exit(1);
  }

  // Load manual tasks
  const manualTasks = await loadManualTasks();
  activityData.manualTasks = manualTasks;

  console.log('Analyzing activity data with Claude...');

  // Initialize Claude client
  const claude = new ClaudeClient();

  // Analyze with Claude
  let analysis;
  try {
    analysis = await claude.analyze(activityData);
    console.log('Claude analysis completed');
  } catch (err) {
    console.error('Claude analysis failed:', err.message);
    // Fallback to basic analysis
    analysis = {
      hours_active: activityData.summary?.activeHours || 0,
      hours_coding: Math.round((activityData.summary?.activeHours || 0) * 0.7),
      hours_meetings: 0,
      hours_research: Math.round((activityData.summary?.activeHours || 0) * 0.3),
      commits_today: activityData.gitActivity?.totalCommits || 0,
      projects: Object.keys(activityData.gitActivity?.byProject || {}),
      tags: ['coding'],
      activity_summary: { time_distribution: 'Based on tracked activity', focus_areas: [] },
      completed_tasks: [],
      in_progress: [],
      research_learning: [],
      blockers: [],
      ai_insights: ['Analysis failed - using fallback data'],
      tomorrow_plan: []
    };
  }

  // Generate markdown
  const markdown = generateMarkdown(analysis, activityData);
  await fs.writeFile(paths.summaryFile, markdown);
  console.log(`Summary saved to: ${paths.summaryFile}`);

  // Update monthly index
  await updateMonthlyIndex(paths);
  console.log('Monthly index updated');

  // Commit and push
  await commitAndPush(`docs: daily summary for ${paths.year}-${paths.month}-${paths.day}`);

  console.log('=== Daily Summary Generator Completed ===');
}

// Run
main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
